<?php

/**
 * @file
 * Contains bkh_employee.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bkh_employee_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bkh_employee module.
    case 'help.page.bkh_employee':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
